development:
  clients:
    default:
      database: bjjc_development
      hosts:
        - localhost:27017
        
development-production:
  clients:
    default:
      database: bjjc_development
      hosts:
        - localhost:27017

production:
  clients:
    default:
      database: bjjc_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: bjjc_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
