
test: &default
  client_id: AYGZKBquUOZ8exH6Hev7r831dLcLGaF-M8jLdMgHkyb6hhsuEtLa9kwX5DZv2FgQboYa7W2Bzw4lG54b
  client_secret: EFD2-w4ZXwPpiR-13acTXFdbuqoi0qMT3Hl9NVzwAFIchFLK_esnglflPB3SrhPYu_vYs8l30HiL9mvW
  mode: sandbox

  ## Credentials for Classic APIs
  # app_id: APP-80W284485P519543T
  # username: jb-us-seller_api1.paypal.com
  # password: WX4WTU3S8MY44S7F
  # signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  ## # With Certificate
  ## cert_path: "config/cert_key.pem"
  # sandbox_email_address: Platform.sdk.seller@gmail.com

development:
  <<: *default

production:
  <<: *default
  mode: live
