#!/bin/bash

#
# run rspec
#

set -ex

if [ ! -d /home/piousbox ] ; then
    # probably running on jenkins
    cp config/mongoid.yml-example config/mongoid.yml
    cp config/database.yml-example config/database.yml
fi

bundle install --path vendor/bundle
bundle exec rspec spec

echo OK
