#!/bin/bash

set -x

cd /home/ubuntu/projects/bjjcollective_railsapp_2015 &&

git pull &&
git fetch &&
git reset origin/master --hard &&

~/.rbenv/versions/2.3.1/bin/bundle  &&

sudo service bjjcollective-app restart &&

echo "bjjc api pulled to production ok"
